name: Austin Teer
title: Austin Teer
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-lock.json
  - package.json
  - postcss.config.js
  - assets/_styles
  - assets/_vendor
